### ISSUE TITLE
Building unit tests fails with NVHPC 21.9 and Intel/19.0.5

### ISSUE THREAD

**Issue by supreethms1809** [shaomeng/SPERR#118]
**Describe the bug**
Building unit tests fails with NVHPC 21.9 and Intel/19.0.5 with the following error in googletest.stderr
```
error: pathspec 'master' did not match any file(s) known to git.
CMake Error at /glade/work/ssuresh/SPERR/intelbuild/googletest/tmp/googletest-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'


gmake[2]: *** [/glade/work/ssuresh/SPERR/intelbuild/googletest/src/googletest-stamp/googletest-download] Error 1
gmake[1]: *** [CMakeFiles/googletest.dir/all] Error 2
gmake: *** [all] Error 2
```

**To Reproduce**
1. Git clone the SPERR respository on to Casper and cd into the directory
2. Module load Intel/19.0.5 or nvhpc/21.9 and cmake
3. Create a build directory and cd into the directory
4. run 'ccmake ..' and press c to configure
5. You can see the error when the configuration hits the googletests part

**Expected and actual behavior**
The expected behaviour is succesful build of unit test. The above issue doesnt happen with GNU compiler on Casper.

**Environment (please complete the following information):**
 - OS: Casper
 - Compiler Intel/19.0.5 and NVHPC/21.9
 - SPERR Version - master branch

**Comment by shaomeng** [comment]
The specific error reported in this issues caused by an upstream change in Google Test. PR #119 has it fixed.

At the same time, Intel 19 and Nvidia 21.9 compilers don't seem to support C++17, which can be tested using the following test program and the [macro definition](https://en.cppreference.com/w/cpp/preprocessor/replace):
```c++
#include <iostream>

int main()
{
  std::cout << __cplusplus << std::endl;
}
```
