### ISSUE TITLE
Need documentation for C++ API

### ISSUE THREAD

**Issue by shaomeng** [shaomeng/SPERR#141]
Maybe C API too!

**Comment by shaomeng** [comment]
The Wiki page (https://github.com/shaomeng/SPERR/wiki) has a section now with documentation on C++ API. Could @[robertu94](https://github.com/robertu94) check if they're clear?

**Comment by robertu94** [comment]
@shaomeng I just got back from vacation, and I'll take a look today.  Not sure why I didn't get a notification about this ...

**Comment by shaomeng** [comment]
@robertu94 Great, thanks! As I'm revamping the code (to eliminate the somewhat awkward`q` parameter), I realize that it most likely will change the C++ API by one or two function calls. I'll keep you posted if that happens!

**Comment by shaomeng** [comment]
Hi @robertu94 , I've finished working on an automatic quantization level selection feature of SPERR, and now you only need to tell the compressor your target PSNR or PWE (point-wise error). Do you want to give a look at the latest documentation that reflects that change? (https://github.com/shaomeng/SPERR/wiki) Thanks!

**Comment by shaomeng** [comment]
It's great to know, thanks again for your contribution and the discussion!
